parent=base
darkMode=false

kcDarkModeClass=pf-v5-theme-dark
contentHashPattern=assets/.*

styles=css/eitas-admin-v3.css

logo=/img/eitas-identity.svg
favIcon=/img/eitas-favicon.svg
favIconType=image/svg+xml

title=EITAS Identity Administration
description=Console d'administration EITAS Identity

scripts=js/eitas-admin-v5.js
