parent=keycloak.v3
deprecatedMode=false

title=EITAS Identity
description=Espace sécurisé de gestion de votre identité professionnelle.

favIcon=img/eitas-favicon.svg
favIconType=image/svg+xml

locales=fr,en
