// Catalogue ISO 3166-1 généré depuis iso-codes 4.18.0.
// Données versionnées : aucune dépendance réseau à l’exécution.

export const COUNTRIES_FR = Object.freeze([
  Object.freeze({"alpha2":"AF","alpha3":"AFG","numeric":4,"name":"Afghanistan"}),
  Object.freeze({"alpha2":"ZA","alpha3":"ZAF","numeric":710,"name":"Afrique du Sud"}),
  Object.freeze({"alpha2":"AL","alpha3":"ALB","numeric":8,"name":"Albanie"}),
  Object.freeze({"alpha2":"DZ","alpha3":"DZA","numeric":12,"name":"Algérie"}),
  Object.freeze({"alpha2":"DE","alpha3":"DEU","numeric":276,"name":"Allemagne"}),
  Object.freeze({"alpha2":"AD","alpha3":"AND","numeric":20,"name":"Andorre"}),
  Object.freeze({"alpha2":"AO","alpha3":"AGO","numeric":24,"name":"Angola"}),
  Object.freeze({"alpha2":"AI","alpha3":"AIA","numeric":660,"name":"Anguilla"}),
  Object.freeze({"alpha2":"AQ","alpha3":"ATA","numeric":10,"name":"Antarctique"}),
  Object.freeze({"alpha2":"AG","alpha3":"ATG","numeric":28,"name":"Antigua-et-Barbuda"}),
  Object.freeze({"alpha2":"SA","alpha3":"SAU","numeric":682,"name":"Arabie saoudite"}),
  Object.freeze({"alpha2":"AR","alpha3":"ARG","numeric":32,"name":"Argentine"}),
  Object.freeze({"alpha2":"AM","alpha3":"ARM","numeric":51,"name":"Arménie"}),
  Object.freeze({"alpha2":"AW","alpha3":"ABW","numeric":533,"name":"Aruba"}),
  Object.freeze({"alpha2":"AU","alpha3":"AUS","numeric":36,"name":"Australie"}),
  Object.freeze({"alpha2":"AT","alpha3":"AUT","numeric":40,"name":"Autriche"}),
  Object.freeze({"alpha2":"AZ","alpha3":"AZE","numeric":31,"name":"Azerbaïdjan"}),
  Object.freeze({"alpha2":"BS","alpha3":"BHS","numeric":44,"name":"Bahamas"}),
  Object.freeze({"alpha2":"BH","alpha3":"BHR","numeric":48,"name":"Bahreïn"}),
  Object.freeze({"alpha2":"BD","alpha3":"BGD","numeric":50,"name":"Bangladesh"}),
  Object.freeze({"alpha2":"BB","alpha3":"BRB","numeric":52,"name":"Barbade"}),
  Object.freeze({"alpha2":"BE","alpha3":"BEL","numeric":56,"name":"Belgique"}),
  Object.freeze({"alpha2":"BZ","alpha3":"BLZ","numeric":84,"name":"Belize"}),
  Object.freeze({"alpha2":"BM","alpha3":"BMU","numeric":60,"name":"Bermudes"}),
  Object.freeze({"alpha2":"BT","alpha3":"BTN","numeric":64,"name":"Bhoutan"}),
  Object.freeze({"alpha2":"MM","alpha3":"MMR","numeric":104,"name":"Birmanie"}),
  Object.freeze({"alpha2":"BO","alpha3":"BOL","numeric":68,"name":"Bolivie, état plurinational de"}),
  Object.freeze({"alpha2":"BQ","alpha3":"BES","numeric":535,"name":"Bonaire, Saint-Eustache et Saba"}),
  Object.freeze({"alpha2":"BA","alpha3":"BIH","numeric":70,"name":"Bosnie-Herzégovine"}),
  Object.freeze({"alpha2":"BW","alpha3":"BWA","numeric":72,"name":"Botswana"}),
  Object.freeze({"alpha2":"BN","alpha3":"BRN","numeric":96,"name":"Brunéi Darussalam"}),
  Object.freeze({"alpha2":"BR","alpha3":"BRA","numeric":76,"name":"Brésil"}),
  Object.freeze({"alpha2":"BG","alpha3":"BGR","numeric":100,"name":"Bulgarie"}),
  Object.freeze({"alpha2":"BF","alpha3":"BFA","numeric":854,"name":"Burkina Faso"}),
  Object.freeze({"alpha2":"BI","alpha3":"BDI","numeric":108,"name":"Burundi"}),
  Object.freeze({"alpha2":"BY","alpha3":"BLR","numeric":112,"name":"Bélarus"}),
  Object.freeze({"alpha2":"BJ","alpha3":"BEN","numeric":204,"name":"Bénin"}),
  Object.freeze({"alpha2":"KH","alpha3":"KHM","numeric":116,"name":"Cambodge"}),
  Object.freeze({"alpha2":"CM","alpha3":"CMR","numeric":120,"name":"Cameroun"}),
  Object.freeze({"alpha2":"CA","alpha3":"CAN","numeric":124,"name":"Canada"}),
  Object.freeze({"alpha2":"CV","alpha3":"CPV","numeric":132,"name":"Cap-Vert"}),
  Object.freeze({"alpha2":"CL","alpha3":"CHL","numeric":152,"name":"Chili"}),
  Object.freeze({"alpha2":"CN","alpha3":"CHN","numeric":156,"name":"Chine"}),
  Object.freeze({"alpha2":"CX","alpha3":"CXR","numeric":162,"name":"Christmas, Île"}),
  Object.freeze({"alpha2":"CY","alpha3":"CYP","numeric":196,"name":"Chypre"}),
  Object.freeze({"alpha2":"CC","alpha3":"CCK","numeric":166,"name":"Cocos (Keeling), Îles"}),
  Object.freeze({"alpha2":"CO","alpha3":"COL","numeric":170,"name":"Colombie"}),
  Object.freeze({"alpha2":"KM","alpha3":"COM","numeric":174,"name":"Comores"}),
  Object.freeze({"alpha2":"KR","alpha3":"KOR","numeric":410,"name":"Corée, République de"}),
  Object.freeze({"alpha2":"KP","alpha3":"PRK","numeric":408,"name":"Corée, République populaire démocratique de"}),
  Object.freeze({"alpha2":"CR","alpha3":"CRI","numeric":188,"name":"Costa Rica"}),
  Object.freeze({"alpha2":"HR","alpha3":"HRV","numeric":191,"name":"Croatie"}),
  Object.freeze({"alpha2":"CU","alpha3":"CUB","numeric":192,"name":"Cuba"}),
  Object.freeze({"alpha2":"CW","alpha3":"CUW","numeric":531,"name":"Curaçao"}),
  Object.freeze({"alpha2":"CI","alpha3":"CIV","numeric":384,"name":"Côte d'Ivoire"}),
  Object.freeze({"alpha2":"DK","alpha3":"DNK","numeric":208,"name":"Danemark"}),
  Object.freeze({"alpha2":"DJ","alpha3":"DJI","numeric":262,"name":"Djibouti"}),
  Object.freeze({"alpha2":"DM","alpha3":"DMA","numeric":212,"name":"Dominique"}),
  Object.freeze({"alpha2":"ES","alpha3":"ESP","numeric":724,"name":"Espagne"}),
  Object.freeze({"alpha2":"EE","alpha3":"EST","numeric":233,"name":"Estonie"}),
  Object.freeze({"alpha2":"SZ","alpha3":"SWZ","numeric":748,"name":"Eswatini"}),
  Object.freeze({"alpha2":"FJ","alpha3":"FJI","numeric":242,"name":"Fidji"}),
  Object.freeze({"alpha2":"FI","alpha3":"FIN","numeric":246,"name":"Finlande"}),
  Object.freeze({"alpha2":"FR","alpha3":"FRA","numeric":250,"name":"France"}),
  Object.freeze({"alpha2":"GA","alpha3":"GAB","numeric":266,"name":"Gabon"}),
  Object.freeze({"alpha2":"GM","alpha3":"GMB","numeric":270,"name":"Gambie"}),
  Object.freeze({"alpha2":"GH","alpha3":"GHA","numeric":288,"name":"Ghana"}),
  Object.freeze({"alpha2":"GI","alpha3":"GIB","numeric":292,"name":"Gibraltar"}),
  Object.freeze({"alpha2":"GD","alpha3":"GRD","numeric":308,"name":"Grenade"}),
  Object.freeze({"alpha2":"GL","alpha3":"GRL","numeric":304,"name":"Groënland"}),
  Object.freeze({"alpha2":"GR","alpha3":"GRC","numeric":300,"name":"Grèce"}),
  Object.freeze({"alpha2":"GP","alpha3":"GLP","numeric":312,"name":"Guadeloupe"}),
  Object.freeze({"alpha2":"GU","alpha3":"GUM","numeric":316,"name":"Guam"}),
  Object.freeze({"alpha2":"GT","alpha3":"GTM","numeric":320,"name":"Guatemala"}),
  Object.freeze({"alpha2":"GG","alpha3":"GGY","numeric":831,"name":"Guernesey"}),
  Object.freeze({"alpha2":"GN","alpha3":"GIN","numeric":324,"name":"Guinée"}),
  Object.freeze({"alpha2":"GQ","alpha3":"GNQ","numeric":226,"name":"Guinée Équatoriale"}),
  Object.freeze({"alpha2":"GW","alpha3":"GNB","numeric":624,"name":"Guinée-Bissau"}),
  Object.freeze({"alpha2":"GY","alpha3":"GUY","numeric":328,"name":"Guyana"}),
  Object.freeze({"alpha2":"GF","alpha3":"GUF","numeric":254,"name":"Guyane française"}),
  Object.freeze({"alpha2":"GE","alpha3":"GEO","numeric":268,"name":"Géorgie"}),
  Object.freeze({"alpha2":"GS","alpha3":"SGS","numeric":239,"name":"Géorgie du Sud et les îles Sandwich du Sud"}),
  Object.freeze({"alpha2":"HT","alpha3":"HTI","numeric":332,"name":"Haïti"}),
  Object.freeze({"alpha2":"HN","alpha3":"HND","numeric":340,"name":"Honduras"}),
  Object.freeze({"alpha2":"HK","alpha3":"HKG","numeric":344,"name":"Hong Kong"}),
  Object.freeze({"alpha2":"HU","alpha3":"HUN","numeric":348,"name":"Hongrie"}),
  Object.freeze({"alpha2":"IN","alpha3":"IND","numeric":356,"name":"Inde"}),
  Object.freeze({"alpha2":"ID","alpha3":"IDN","numeric":360,"name":"Indonésie"}),
  Object.freeze({"alpha2":"IQ","alpha3":"IRQ","numeric":368,"name":"Irak"}),
  Object.freeze({"alpha2":"IR","alpha3":"IRN","numeric":364,"name":"Iran, République islamique d'"}),
  Object.freeze({"alpha2":"IE","alpha3":"IRL","numeric":372,"name":"Irlande"}),
  Object.freeze({"alpha2":"IS","alpha3":"ISL","numeric":352,"name":"Islande"}),
  Object.freeze({"alpha2":"IL","alpha3":"ISR","numeric":376,"name":"Israël"}),
  Object.freeze({"alpha2":"IT","alpha3":"ITA","numeric":380,"name":"Italie"}),
  Object.freeze({"alpha2":"JM","alpha3":"JAM","numeric":388,"name":"Jamaïque"}),
  Object.freeze({"alpha2":"JP","alpha3":"JPN","numeric":392,"name":"Japon"}),
  Object.freeze({"alpha2":"JE","alpha3":"JEY","numeric":832,"name":"Jersey"}),
  Object.freeze({"alpha2":"JO","alpha3":"JOR","numeric":400,"name":"Jordanie"}),
  Object.freeze({"alpha2":"KZ","alpha3":"KAZ","numeric":398,"name":"Kazakhstan"}),
  Object.freeze({"alpha2":"KE","alpha3":"KEN","numeric":404,"name":"Kenya"}),
  Object.freeze({"alpha2":"KG","alpha3":"KGZ","numeric":417,"name":"Kirghizistan"}),
  Object.freeze({"alpha2":"KI","alpha3":"KIR","numeric":296,"name":"Kiribati"}),
  Object.freeze({"alpha2":"KW","alpha3":"KWT","numeric":414,"name":"Koweït"}),
  Object.freeze({"alpha2":"LA","alpha3":"LAO","numeric":418,"name":"Lao, République démocratique populaire"}),
  Object.freeze({"alpha2":"LS","alpha3":"LSO","numeric":426,"name":"Lesotho"}),
  Object.freeze({"alpha2":"LV","alpha3":"LVA","numeric":428,"name":"Lettonie"}),
  Object.freeze({"alpha2":"LB","alpha3":"LBN","numeric":422,"name":"Liban"}),
  Object.freeze({"alpha2":"LY","alpha3":"LBY","numeric":434,"name":"Libye"}),
  Object.freeze({"alpha2":"LR","alpha3":"LBR","numeric":430,"name":"Libéria"}),
  Object.freeze({"alpha2":"LI","alpha3":"LIE","numeric":438,"name":"Liechtenstein"}),
  Object.freeze({"alpha2":"LT","alpha3":"LTU","numeric":440,"name":"Lituanie"}),
  Object.freeze({"alpha2":"LU","alpha3":"LUX","numeric":442,"name":"Luxembourg"}),
  Object.freeze({"alpha2":"MO","alpha3":"MAC","numeric":446,"name":"Macau"}),
  Object.freeze({"alpha2":"MK","alpha3":"MKD","numeric":807,"name":"Macédoine du Nord"}),
  Object.freeze({"alpha2":"MG","alpha3":"MDG","numeric":450,"name":"Madagascar"}),
  Object.freeze({"alpha2":"MY","alpha3":"MYS","numeric":458,"name":"Malaisie"}),
  Object.freeze({"alpha2":"MW","alpha3":"MWI","numeric":454,"name":"Malawi"}),
  Object.freeze({"alpha2":"MV","alpha3":"MDV","numeric":462,"name":"Maldives"}),
  Object.freeze({"alpha2":"ML","alpha3":"MLI","numeric":466,"name":"Mali"}),
  Object.freeze({"alpha2":"FK","alpha3":"FLK","numeric":238,"name":"Malouines, Îles (Falkland)"}),
  Object.freeze({"alpha2":"MT","alpha3":"MLT","numeric":470,"name":"Malte"}),
  Object.freeze({"alpha2":"MA","alpha3":"MAR","numeric":504,"name":"Maroc"}),
  Object.freeze({"alpha2":"MQ","alpha3":"MTQ","numeric":474,"name":"Martinique"}),
  Object.freeze({"alpha2":"MU","alpha3":"MUS","numeric":480,"name":"Maurice"}),
  Object.freeze({"alpha2":"MR","alpha3":"MRT","numeric":478,"name":"Mauritanie"}),
  Object.freeze({"alpha2":"YT","alpha3":"MYT","numeric":175,"name":"Mayotte"}),
  Object.freeze({"alpha2":"MX","alpha3":"MEX","numeric":484,"name":"Mexique"}),
  Object.freeze({"alpha2":"FM","alpha3":"FSM","numeric":583,"name":"Micronésie, États fédérés de"}),
  Object.freeze({"alpha2":"MD","alpha3":"MDA","numeric":498,"name":"Moldova, République de"}),
  Object.freeze({"alpha2":"MC","alpha3":"MCO","numeric":492,"name":"Monaco"}),
  Object.freeze({"alpha2":"MN","alpha3":"MNG","numeric":496,"name":"Mongolie"}),
  Object.freeze({"alpha2":"MS","alpha3":"MSR","numeric":500,"name":"Montserrat"}),
  Object.freeze({"alpha2":"ME","alpha3":"MNE","numeric":499,"name":"Monténégro"}),
  Object.freeze({"alpha2":"MZ","alpha3":"MOZ","numeric":508,"name":"Mozambique"}),
  Object.freeze({"alpha2":"NA","alpha3":"NAM","numeric":516,"name":"Namibie"}),
  Object.freeze({"alpha2":"NR","alpha3":"NRU","numeric":520,"name":"Nauru"}),
  Object.freeze({"alpha2":"NI","alpha3":"NIC","numeric":558,"name":"Nicaragua"}),
  Object.freeze({"alpha2":"NE","alpha3":"NER","numeric":562,"name":"Niger"}),
  Object.freeze({"alpha2":"NG","alpha3":"NGA","numeric":566,"name":"Nigeria"}),
  Object.freeze({"alpha2":"NU","alpha3":"NIU","numeric":570,"name":"Nioue"}),
  Object.freeze({"alpha2":"NO","alpha3":"NOR","numeric":578,"name":"Norvège"}),
  Object.freeze({"alpha2":"NC","alpha3":"NCL","numeric":540,"name":"Nouvelle-Calédonie"}),
  Object.freeze({"alpha2":"NZ","alpha3":"NZL","numeric":554,"name":"Nouvelle-Zélande"}),
  Object.freeze({"alpha2":"NP","alpha3":"NPL","numeric":524,"name":"Népal"}),
  Object.freeze({"alpha2":"OM","alpha3":"OMN","numeric":512,"name":"Oman"}),
  Object.freeze({"alpha2":"UG","alpha3":"UGA","numeric":800,"name":"Ouganda"}),
  Object.freeze({"alpha2":"UZ","alpha3":"UZB","numeric":860,"name":"Ouzbékistan"}),
  Object.freeze({"alpha2":"PK","alpha3":"PAK","numeric":586,"name":"Pakistan"}),
  Object.freeze({"alpha2":"PW","alpha3":"PLW","numeric":585,"name":"Palaos"}),
  Object.freeze({"alpha2":"PS","alpha3":"PSE","numeric":275,"name":"Palestine, État de"}),
  Object.freeze({"alpha2":"PA","alpha3":"PAN","numeric":591,"name":"Panama"}),
  Object.freeze({"alpha2":"PG","alpha3":"PNG","numeric":598,"name":"Papouasie-Nouvelle-Guinée"}),
  Object.freeze({"alpha2":"PY","alpha3":"PRY","numeric":600,"name":"Paraguay"}),
  Object.freeze({"alpha2":"NL","alpha3":"NLD","numeric":528,"name":"Pays-Bas"}),
  Object.freeze({"alpha2":"PH","alpha3":"PHL","numeric":608,"name":"Philippines"}),
  Object.freeze({"alpha2":"PL","alpha3":"POL","numeric":616,"name":"Pologne"}),
  Object.freeze({"alpha2":"PF","alpha3":"PYF","numeric":258,"name":"Polynésie française"}),
  Object.freeze({"alpha2":"PR","alpha3":"PRI","numeric":630,"name":"Porto Rico"}),
  Object.freeze({"alpha2":"PT","alpha3":"PRT","numeric":620,"name":"Portugal"}),
  Object.freeze({"alpha2":"PE","alpha3":"PER","numeric":604,"name":"Pérou"}),
  Object.freeze({"alpha2":"QA","alpha3":"QAT","numeric":634,"name":"Qatar"}),
  Object.freeze({"alpha2":"RO","alpha3":"ROU","numeric":642,"name":"Roumanie"}),
  Object.freeze({"alpha2":"GB","alpha3":"GBR","numeric":826,"name":"Royaume-Uni"}),
  Object.freeze({"alpha2":"RU","alpha3":"RUS","numeric":643,"name":"Russie, Fédération de"}),
  Object.freeze({"alpha2":"RW","alpha3":"RWA","numeric":646,"name":"Rwanda"}),
  Object.freeze({"alpha2":"CF","alpha3":"CAF","numeric":140,"name":"République centrafricaine"}),
  Object.freeze({"alpha2":"DO","alpha3":"DOM","numeric":214,"name":"République dominicaine"}),
  Object.freeze({"alpha2":"CG","alpha3":"COG","numeric":178,"name":"République du Congo"}),
  Object.freeze({"alpha2":"CD","alpha3":"COD","numeric":180,"name":"République démocratique du Congo"}),
  Object.freeze({"alpha2":"RE","alpha3":"REU","numeric":638,"name":"Réunion, Île de la"}),
  Object.freeze({"alpha2":"EH","alpha3":"ESH","numeric":732,"name":"Sahara occidental"}),
  Object.freeze({"alpha2":"BL","alpha3":"BLM","numeric":652,"name":"Saint-Barthélemy"}),
  Object.freeze({"alpha2":"KN","alpha3":"KNA","numeric":659,"name":"Saint-Christophe-et-Niévès"}),
  Object.freeze({"alpha2":"SM","alpha3":"SMR","numeric":674,"name":"Saint-Marin"}),
  Object.freeze({"alpha2":"MF","alpha3":"MAF","numeric":663,"name":"Saint-Martin (partie française)"}),
  Object.freeze({"alpha2":"SX","alpha3":"SXM","numeric":534,"name":"Saint-Martin (partie néerlandaise)"}),
  Object.freeze({"alpha2":"PM","alpha3":"SPM","numeric":666,"name":"Saint-Pierre-et-Miquelon"}),
  Object.freeze({"alpha2":"VA","alpha3":"VAT","numeric":336,"name":"Saint-Siège (état de la cité du Vatican)"}),
  Object.freeze({"alpha2":"VC","alpha3":"VCT","numeric":670,"name":"Saint-Vincent-et-les-Grenadines"}),
  Object.freeze({"alpha2":"SH","alpha3":"SHN","numeric":654,"name":"Sainte-Hélène, Ascension et Tristan da Cunha"}),
  Object.freeze({"alpha2":"LC","alpha3":"LCA","numeric":662,"name":"Sainte-Lucie"}),
  Object.freeze({"alpha2":"SB","alpha3":"SLB","numeric":90,"name":"Salomon, Îles"}),
  Object.freeze({"alpha2":"SV","alpha3":"SLV","numeric":222,"name":"Salvador"}),
  Object.freeze({"alpha2":"WS","alpha3":"WSM","numeric":882,"name":"Samoa"}),
  Object.freeze({"alpha2":"AS","alpha3":"ASM","numeric":16,"name":"Samoa américaines"}),
  Object.freeze({"alpha2":"ST","alpha3":"STP","numeric":678,"name":"Sao Tomé-et-Principe"}),
  Object.freeze({"alpha2":"RS","alpha3":"SRB","numeric":688,"name":"Serbie"}),
  Object.freeze({"alpha2":"SC","alpha3":"SYC","numeric":690,"name":"Seychelles"}),
  Object.freeze({"alpha2":"SL","alpha3":"SLE","numeric":694,"name":"Sierra Leone"}),
  Object.freeze({"alpha2":"SG","alpha3":"SGP","numeric":702,"name":"Singapour"}),
  Object.freeze({"alpha2":"SK","alpha3":"SVK","numeric":703,"name":"Slovaquie"}),
  Object.freeze({"alpha2":"SI","alpha3":"SVN","numeric":705,"name":"Slovénie"}),
  Object.freeze({"alpha2":"SO","alpha3":"SOM","numeric":706,"name":"Somalie"}),
  Object.freeze({"alpha2":"SD","alpha3":"SDN","numeric":729,"name":"Soudan"}),
  Object.freeze({"alpha2":"SS","alpha3":"SSD","numeric":728,"name":"Soudan du Sud"}),
  Object.freeze({"alpha2":"LK","alpha3":"LKA","numeric":144,"name":"Sri Lanka"}),
  Object.freeze({"alpha2":"CH","alpha3":"CHE","numeric":756,"name":"Suisse"}),
  Object.freeze({"alpha2":"SR","alpha3":"SUR","numeric":740,"name":"Surinam"}),
  Object.freeze({"alpha2":"SE","alpha3":"SWE","numeric":752,"name":"Suède"}),
  Object.freeze({"alpha2":"SJ","alpha3":"SJM","numeric":744,"name":"Svalbard et île Jan Mayen"}),
  Object.freeze({"alpha2":"SY","alpha3":"SYR","numeric":760,"name":"Syrienne, République arabe"}),
  Object.freeze({"alpha2":"SN","alpha3":"SEN","numeric":686,"name":"Sénégal"}),
  Object.freeze({"alpha2":"TJ","alpha3":"TJK","numeric":762,"name":"Tadjikistan"}),
  Object.freeze({"alpha2":"TZ","alpha3":"TZA","numeric":834,"name":"Tanzanie, République unie de"}),
  Object.freeze({"alpha2":"TW","alpha3":"TWN","numeric":158,"name":"Taïwan, province de Chine"}),
  Object.freeze({"alpha2":"TD","alpha3":"TCD","numeric":148,"name":"Tchad"}),
  Object.freeze({"alpha2":"CZ","alpha3":"CZE","numeric":203,"name":"Tchéquie"}),
  Object.freeze({"alpha2":"TF","alpha3":"ATF","numeric":260,"name":"Terres australes françaises"}),
  Object.freeze({"alpha2":"IO","alpha3":"IOT","numeric":86,"name":"Territoire britannique de l'océan Indien"}),
  Object.freeze({"alpha2":"TH","alpha3":"THA","numeric":764,"name":"Thaïlande"}),
  Object.freeze({"alpha2":"TL","alpha3":"TLS","numeric":626,"name":"Timor oriental"}),
  Object.freeze({"alpha2":"TG","alpha3":"TGO","numeric":768,"name":"Togo"}),
  Object.freeze({"alpha2":"TK","alpha3":"TKL","numeric":772,"name":"Tokelau"}),
  Object.freeze({"alpha2":"TO","alpha3":"TON","numeric":776,"name":"Tonga"}),
  Object.freeze({"alpha2":"TT","alpha3":"TTO","numeric":780,"name":"Trinité-et-Tobago"}),
  Object.freeze({"alpha2":"TN","alpha3":"TUN","numeric":788,"name":"Tunisie"}),
  Object.freeze({"alpha2":"TM","alpha3":"TKM","numeric":795,"name":"Turkménistan"}),
  Object.freeze({"alpha2":"TR","alpha3":"TUR","numeric":792,"name":"Turquie"}),
  Object.freeze({"alpha2":"TV","alpha3":"TUV","numeric":798,"name":"Tuvalu"}),
  Object.freeze({"alpha2":"UA","alpha3":"UKR","numeric":804,"name":"Ukraine"}),
  Object.freeze({"alpha2":"UY","alpha3":"URY","numeric":858,"name":"Uruguay"}),
  Object.freeze({"alpha2":"VU","alpha3":"VUT","numeric":548,"name":"Vanuatu"}),
  Object.freeze({"alpha2":"VN","alpha3":"VNM","numeric":704,"name":"Viêt Nam"}),
  Object.freeze({"alpha2":"VE","alpha3":"VEN","numeric":862,"name":"Vénézuela, république bolivarienne du"}),
  Object.freeze({"alpha2":"WF","alpha3":"WLF","numeric":876,"name":"Wallis et Futuna"}),
  Object.freeze({"alpha2":"YE","alpha3":"YEM","numeric":887,"name":"Yémen"}),
  Object.freeze({"alpha2":"ZM","alpha3":"ZMB","numeric":894,"name":"Zambie"}),
  Object.freeze({"alpha2":"ZW","alpha3":"ZWE","numeric":716,"name":"Zimbabwe"}),
  Object.freeze({"alpha2":"AX","alpha3":"ALA","numeric":248,"name":"Åland, Îles"}),
  Object.freeze({"alpha2":"EG","alpha3":"EGY","numeric":818,"name":"Égypte"}),
  Object.freeze({"alpha2":"AE","alpha3":"ARE","numeric":784,"name":"Émirats arabes unis"}),
  Object.freeze({"alpha2":"EC","alpha3":"ECU","numeric":218,"name":"Équateur"}),
  Object.freeze({"alpha2":"ER","alpha3":"ERI","numeric":232,"name":"Érythrée"}),
  Object.freeze({"alpha2":"US","alpha3":"USA","numeric":840,"name":"États-Unis"}),
  Object.freeze({"alpha2":"ET","alpha3":"ETH","numeric":231,"name":"Éthiopie"}),
  Object.freeze({"alpha2":"BV","alpha3":"BVT","numeric":74,"name":"Île Bouvet"}),
  Object.freeze({"alpha2":"IM","alpha3":"IMN","numeric":833,"name":"Île de Man"}),
  Object.freeze({"alpha2":"NF","alpha3":"NFK","numeric":574,"name":"Île Norfolk"}),
  Object.freeze({"alpha2":"KY","alpha3":"CYM","numeric":136,"name":"Îles Caïmans"}),
  Object.freeze({"alpha2":"CK","alpha3":"COK","numeric":184,"name":"Îles Cook"}),
  Object.freeze({"alpha2":"FO","alpha3":"FRO","numeric":234,"name":"Îles Féroé"}),
  Object.freeze({"alpha2":"HM","alpha3":"HMD","numeric":334,"name":"Îles Heard-et-MacDonald"}),
  Object.freeze({"alpha2":"MP","alpha3":"MNP","numeric":580,"name":"Îles Mariannes du Nord"}),
  Object.freeze({"alpha2":"MH","alpha3":"MHL","numeric":584,"name":"Îles Marshall"}),
  Object.freeze({"alpha2":"UM","alpha3":"UMI","numeric":581,"name":"Îles mineures éloignées des États-Unis"}),
  Object.freeze({"alpha2":"PN","alpha3":"PCN","numeric":612,"name":"Îles Pitcairn"}),
  Object.freeze({"alpha2":"TC","alpha3":"TCA","numeric":796,"name":"Îles Turques-et-Caïques"}),
  Object.freeze({"alpha2":"VG","alpha3":"VGB","numeric":92,"name":"Îles Vierges britanniques"}),
  Object.freeze({"alpha2":"VI","alpha3":"VIR","numeric":850,"name":"Îles Vierges, États-Unis"}),
])

const COUNTRIES_BY_ALPHA2 = new Map(
  COUNTRIES_FR.map(country => [
    country.alpha2,
    country,
  ])
)

export function getCountryByAlpha2(value) {
  return COUNTRIES_BY_ALPHA2.get(
    String(value || '').trim().toUpperCase()
  ) || null
}
